### ISSUE TITLE
Installing this crate breaks build

### ISSUE THREAD

**Issue by namse** [orxfun/orx-linked-list#24]
![image](https://github.com/orxfun/orx-linked-list/assets/3580430/2309abe3-bd70-4eff-b48a-86038fa37691)

**Comment by orxfun** [comment]
@namse thanks for reporting the issue, will fix this problem shortly.

**Comment by orxfun** [comment]
@namse The problem is fixed and published. Could you please try using:
* orx-linked-list = "2.3.0"

Please let me know if you encounter further issues.
